edge('Tom', 'PROPNnsubjVERB', 'love', 0).
edge('love', 'VERB_PREDICATE_OF', 0, 0).
edge('fishing', 'NOUNobjVERB', 'love', 0).
edge(0, 'ABOUT', 'fishing', 0).
edge('.', 'PUNCTpunctVERB', 'love', 0).
edge('he', 'PRONnsubjVERB', 'go', 1).
edge('go', 'VERB_PREDICATE_OF', 1, 1).
edge('fishing', 'VERBxcompVERB', 'go', 1).
edge('everyday', 'NOUNobjVERB', 'fishing', 1).
edge(1, 'ABOUT', 'everyday', 1).
edge('.', 'PUNCTpunctVERB', 'go', 1).
